### PR TITLE
Fixed panning before indicators begin bug

### LINKED ISSUE #254: Panning before indicators breaks line render
capture

Rendering line breaks on `NaN` when panning to penultimate data before beginning of indicators on primary chart

### PR DESCRIPTION
**Pull request by djmiley**
Resolves #254

### CODE REVIEW

**Comment by jleft** [comment]
`d3.min()` and `d3.max()` both ignore `undefined` values, unlike `Math.min()` and `Math.max()`, which is what is what we want to do. Could we do something like this, which should solved the issue and avoid the loop before?

```js
if (bollingerBandsShown) {
    var bollingerBandsVisibleDataObject = visibleData.map(function(d) { return d.bollingerBands; });
    var bollingerBandsExtent = fc.util.extent(bollingerBandsVisibleDataObject, ['lower', 'upper']);
    extent[0] = d3.min([bollingerBandsExtent[0], extent[0]]);
    extent[1] = d3.max([bollingerBandsExtent[1], extent[1]]);
}
if (movingAverageShown) {
    var movingAverageExtent = fc.util.extent(visibleData, 'movingAverage');
    extent[0] = d3.min([movingAverageExtent[0], extent[0]]);
    extent[1] = d3.max([movingAverageExtent[1], extent[1]]);
}
```

File: src/assets/js/chart/primary.js [hunk 1]
```diff
@@ -44,7 +44,18 @@
         }
         var extent = fc.util.extent(visibleData, extentAccessor);
 
-        if (currentIndicators.length) {
+        var visibleDataIndicatorsUndefined = (function() {
```
Comment (jleft) [inline src/assets/js/chart/primary.js]: I think this assumes that if an indicator will has an `undefined` value on a datum, the value for all other indicators will also be `undefined`, but this may not necessarily be the case, for example if their window length is configured differently.
